#define X_LT &trans
#define X_LM &trans
#define X_LB &trans
#define X_MT &trans
#define X_MM &trans
#define X_MB &trans
#define X_MH &trans
#define X_RT &trans
#define X_RM &trans
#define X_RB &trans
